### ISSUE TITLE
Take iPad off the list of browsers..?

### ISSUE THREAD

**Issue by ghost** [sebarmeli/JS-Redirection-Mobile-Site#12]
Hi, I would like to allow the iPad to go to the noraml version of the site instead of being redirected to the mobile version, is there an option/code a can change to make this happen..?

**Comment by sebarmeli** [comment]
Hi there,
I was going to put this option in the version 0.8. I'll close off the issue when I release it.

Cheers,
Sebastiano

**Comment by auroraconsulting** [comment]
I think it would be the option to exclude all tablet devices.

I know it means more work, but the end result would be awesome.

Thanks,
Scott

**Comment by sebarmeli** [comment]
are you suggesting any specific device apart from Ipad? ..Kindle? 

Thanks,
Sebastiano

**Comment by sebarmeli** [comment]
Version 0.8 release. Ipad excluded from the list of mobile devices, you can enable redirection for it using "ipad_redirection" : "true" option

**Comment by ghost** [comment]
This is awesome, thanks man your a star..!

**Comment by auroraconsulting** [comment]
Yes, I was thinking that all Android tablets should be treated in a similar way (if possible).

**Comment by sebarmeli** [comment]
Updated for version 0.8.5 with the support for Android devices. Let me know if it suits your needs
