### ISSUE TITLE
Script has stopped working in some android devices

### ISSUE THREAD

**Issue by whicks1** [sebarmeli/JS-Redirection-Mobile-Site#19]
Hey, wonderfully easy script.  We deployed it to several pages on a plone-based cms site recently and it worked fine on a number of devices when we first tested, but for some reason we are finding that some android devices are failing to execute the script. We've had it fail on several droids and a newer samsung infuse, but it works fine when using firefox's user-agent switch and setting the UA to the various flavors of android. One tester claims that the site did redirect correctly several months ago, but that it now fails.  This would make me think the problem was with the the device dealing with cookies/storage, but the samsung infuse we tested on had never visited the site before.  It continues to work fine in IOS devices so I'm guessing something in the expression that test for android?

I also found this site with a big Regex test for devices, maybe useful for yours as well? http://detectmobilebrowsers.com/ 

Our Site: library.unt.edu.

Thanks for your hard work!

**Comment by auroraconsulting** [comment]
I have also experienced this issue, most recently with the Kindle Fire.

I have added "silk" to the tablet regex and the Kindle Fire is now filtered appropriately.

**Comment by sebarmeli** [comment]
Added "silk" to the regex. Thanks
