### ISSUE TITLE
Downloaded the Latest Version. Issue with noredirection

### ISSUE THREAD

**Issue by derekang** [sebarmeli/JS-Redirection-Mobile-Site#21]

**Comment by derekang** [comment]
I have these 2 lines in the configuration       

noredirection_param : "noredirection",
 mobile_url : "mobile.mydomain.com"

I tried accessing mydomain.com?noredirection=true, it still redirect me to my mobile site. Can you help in this issue? thanks!

**Comment by derekang** [comment]
any support?

**Comment by sebarmeli** [comment]
Check out the new version just released, it should work fine now. Watch out you need to use "mobile_redirect=false" now
