### ISSUE TITLE
Galaxy Tab 10"

### ISSUE THREAD

**Issue by dumorian** [sebarmeli/JS-Redirection-Mobile-Site#23]
The tablet_redirection: true does not work for Samsung Galaxy Tab 10". I changed android 0.5 to android and it works but I wonder if I broke something else on other devices. FYI, the UA for this device is shown in my logs as:

Mozilla/5.0 (Linux; U; Android 3.2; en-us; GT-P7510 Build/HTJ85B) AppleWebKit/534.13 (KHTML, like Gecko) Version/4.0 Safari/5

so I suppose other than android, we have GT-P7510 as a potential for defining the device.

Great script!

**Comment by sebarmeli** [comment]
It should work now for Galaxy Tab 10''. Check out the new version.
