### ISSUE TITLE
Using redirection_mobile_self.js, It's redirecting the iPad. How can I stop this?

### ISSUE THREAD

**Issue by jthrashr** [sebarmeli/JS-Redirection-Mobile-Site#24]
I'd like to use the redirection_mobile_self.js since it's less code, but is there a way to make it stop redirecting the iPad?

**Comment by jthrashr** [comment]
I added the following code, and it seems to work now, so yay.

Thanks for writing this btw.

```
            // Check if the device is a Tablet such as iPad, Samsung Tab, Motorola Xoom or Amazon Kindle
if (!!(agent.match(/(iPad|SCH-I800|xoom|kindle)/i))) {

    // Check if the redirection needs to happen for iPad
    var isUATablet = (config.tablet_redirection === TRUE || !!config.tablet_url) ? true : false;
    isUAMobile = false;
}
```

**Comment by clemmonsmc** [comment]
The agent.match regex value "mobile" is what snags the iPad.  Seems like the inclusion of "mobile" in the regex would be a catch all, no?

**Comment by sebarmeli** [comment]
The new version 1.0.0 fixes the issue.
