### ISSUE TITLE
Is still working script?

### ISSUE THREAD

**Issue by wordpresschef** [sebarmeli/JS-Redirection-Mobile-Site#29]
Hi,

I've just installed this script on a desktop version website: http://www.lenotti.it/

but when I try to  "force" the desktop version from a mobile device  with the suggested URL

http://www.lenotti.it?noredirection=true 

the script keep redirecting me to the mobile website http://mobile.lenotti.it

Could you give me any hints?

Thank you very much

Dimitri

**Comment by sebarmeli** [comment]
Hi Dimitri,
can you try out the new version just released and let me know how you go?

Thanks!
