### ISSUE TITLE
Samsung Galaxy Tab Still Not Working?

### ISSUE THREAD

**Issue by derekang** [sebarmeli/JS-Redirection-Mobile-Site#32]
Hi, i just used this new version of redirection script. It seems that the redirection for samsung galaxy tab is still not working. Any advice?

**Comment by Prabaharancs** [comment]
I too checked not working in Samsung galaxy tab and Google nexus 7 while browsing through Opera mobile

**Comment by WChoy** [comment]
Your going to move the test for setting isUATablet ahead or isUAMobile.  
According to Google https://developers.google.com/chrome/mobile/docs/user-agent
  Phone pattern: 'Android' + 'Chrome/[.0-9]\* Mobile'
  Tablet pattern: 'Android' + 'Chrome/[.0-9]\* (?!Mobile)'
So if the word "Mobile" appear in the User Agent, you can overwrite isUATablet .

The Samsung galaxy should already match on  "SCH-I800" :
Mozilla/5.0 (Linux; U; Android 2.2; en-us; SCH-I800 Build/FROYO) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
You probably have an issue somewhere else.

PS: Your doing a case-insensitive agent.match for tablets, but you already did  a toLowerCase() on the the agent variable.

**Comment by mmbash** [comment]
Hi,

i modified the tablet regex to make it work with Galaxy Tab 2 and some others

 // Check if the device is a Tablet such as iPad, Samsung Tab, Motorola Xoom or Amazon Kindle
        if (!!(agent.match(/(iPad|SCH-I|xoom|NOOK|silk|kindle|GT-P|touchpad|kindle|sch-t|viewpad|bolt|playbook)/i))) {

Nice script.

Best,

Mike

**Comment by sebarmeli** [comment]
thanks @mmbash 

I included your update into version 1.0.1
