### ISSUE TITLE
Example Error: Var name typo error

### ISSUE THREAD

**Issue by Prabaharancs** [sebarmeli/JS-Redirection-Mobile-Site#33]
Hi,

I copy pasted the below code from example and found that tablet redirect not working.
    SA.redirection_mobile ({
        mobile_url : "mobile.whatever.com",
        tablet_url : "tablet.whatever.com",
    });

Finally I found that, you have mentioned var "tablet_host" as "tablet_url". So please correctthat typo error in the examples section. Now its working fine, thanks for the plugin.

**Comment by sebarmeli** [comment]
Should be fixed

**Comment by sebarmeli** [comment]
Version 1.0.1 fixed it
